# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
# Project
mod_version=1.0.0
maven_group=com.madgique.jeihoversearch
mod_class_name = JEIHoverSearchMod
archives_base_name=jei_hover_search
enabled_platforms=forge,fabric

# Minecraft properties
minecraft_version=1.20.1

# Dependencies
architectury_version=9.2.14
fabric_loader_version=0.15.11
fabric_api_version=0.92.2+1.20.1
jei_version=15.2.0.27
forge_version=47.3.0