# Mod infos
mod_display_name = JEI Hover Search

mod_description = Search items in JEI by hovering over them and pressing a key
mod_authors = Madgique
mod_id = jei_hover_search
mod_license = LGPLv2.1
mod_public_url = https://github.com/Madgique/jei-hover-search
mod_sources = https://github.com/Madgique/jei-hover-search
mod_issue_tracker_url = https://github.com/Madgique/jei-hover-search/issues